# Generated by Django 5.2.17 on 2026-10-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('edge_device_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('capacity', models.IntegerField()),
                ('enrolled', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('mode', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('employer_id', models.CharField(max_length=50)),
                ('employer_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('applicants', models.IntegerField(default=0)),
                ('status', models.CharField(default='open', max_length=50)),
                ('skills_required', models.ManyToManyField(blank=True, to='api.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('cooperative', models.CharField(max_length=200)),
                ('attendance_pct', models.IntegerField(default=0)),
                ('assessment_score', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('employed', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.institute')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.programme')),
                ('skills', models.ManyToManyField(blank=True, to='api.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('issued_date', models.DateField()),
                ('grade', models.CharField(max_length=10)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programme')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trainee')),
            ],
        ),
    ]
