# Generated by Django 5.2.17 on 2026-10-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_logisticsdispatch_timetablesession_hostelblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesession',
            name='end_time',
            field=models.CharField(default='10:30', max_length=20),
        ),
        migrations.AddField(
            model_name='timetablesession',
            name='programme_title',
            field=models.CharField(default='Cooperative Management', max_length=200),
        ),
        migrations.AddField(
            model_name='timetablesession',
            name='start_time',
            field=models.CharField(default='09:00', max_length=20),
        ),
        migrations.AddField(
            model_name='timetablesession',
            name='venue_type',
            field=models.CharField(default='Lecture Hall', max_length=50),
        ),
        migrations.AlterField(
            model_name='timetablesession',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetablesession',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
