# Generated by Django 5.2.17 on 2026-10-01 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_timetablesession_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='applied', max_length=50)),
                ('match_score', models.IntegerField(default=85)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='api.job')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.trainee')),
            ],
        ),
    ]
