# Generated by Django 5.2.17 on 2026-10-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(default='Cooperative Management', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(default=8)),
                ('status', models.CharField(default='active', max_length=50)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='api.institute')),
            ],
        ),
    ]
