# Generated by Django 5.2.17 on 2026-10-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nominee_name', models.CharField(max_length=200)),
                ('nominee_email', models.EmailField(max_length=254)),
                ('nominee_phone', models.CharField(max_length=20)),
                ('nominator_organization', models.CharField(max_length=200)),
                ('nominator_name', models.CharField(max_length=200)),
                ('nominator_designation', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('submitted_on', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='api.programme')),
            ],
        ),
    ]
